---
# handlers file for nomad
- name: systemd reload
  become: yes
  command: /usr/bin/systemctl daemon-reload
     

- name: restart nomad
  become: yes
  service:
    name: "{{ nomad_service_name }}"
    state: restarted
  tags:
    - nomad

- name: reload nomad
  become: yes
  service:
    name: "{{ nomad_service_name }}"
    state: reloaded
  tags:
    - nomad
